"""
Agno LLM Structuring Pipeline
=============================
Handles raw text extraction, semantic chunking, Agno LLM querying,
and post-processing of images and structure.
"""

import os
import re
from core.config import get_logger, IMAGE_DIR
from core.docx import extract_docx_raw_paragraphs
from core.pdf import extract_pdf_raw_paragraphs
from core.chunker import segment_text_into_logical_chunks
from core.llm_engine import query_llm_for_structuring, MedExtractQuestion

logger = get_logger("llm_pipeline")


def pydantic_to_dict(q: MedExtractQuestion) -> dict:
    """Converts a Pydantic MedExtractQuestion model to a plain dict for JSON output."""
    return q.model_dump(mode="json")


def run_llm_pipeline(filepath: str, filename: str, category: str) -> list:
    """
    Full LLM extraction pipeline for a single file:
      1. Physical extraction of paragraphs + image placeholders
      2. Semantic chunking (preserves clinical dossier integrity)
      3. Agno LLM structuring → validated Pydantic objects
      4. Convert to dicts for unified JSON output

    Returns:
        List of question dicts compatible with the rule-based format.
    """
    ext = filename.lower()

    # ── Step 1: Raw paragraph extraction ─────────────────────────────────────
    logger.info(f"[LLM] Extraction des paragraphes bruts de '{filename}'...")
    if ext.endswith(".docx"):
        paragraphs = extract_docx_raw_paragraphs(filepath)
    elif ext.endswith(".pdf"):
        paragraphs = extract_pdf_raw_paragraphs(filepath)
    else:
        logger.warning(f"Format non supporté pour le pipeline LLM: {filename}")
        return []

    if not paragraphs:
        logger.warning(f"[LLM] Aucun paragraphe extrait de '{filename}'.")
        return []

    logger.info(f"[LLM] {len(paragraphs)} paragraphe(s) extrait(s) de '{filename}'.")

    # ── Step 2: Semantic chunking ──────────────────────────────────────────────
    logger.info(f"[LLM] Segmentation sémantique en chunks logiques...")
    chunks = segment_text_into_logical_chunks(paragraphs, max_questions_per_chunk=8)
    logger.info(f"[LLM] {len(chunks)} chunk(s) créé(s) pour '{filename}'.")

    if not chunks:
        logger.warning(f"[LLM] Aucun chunk généré pour '{filename}'.")
        return []

    # ── Step 3: LLM structuring per chunk ────────────────────────────────────
    all_questions: list[MedExtractQuestion] = []
    for chunk_idx, chunk_text in enumerate(chunks):
        logger.info(
            f"[LLM] Traitement chunk {chunk_idx + 1}/{len(chunks)} "
            f"({len(chunk_text)} chars)..."
        )
        try:
            extracted = query_llm_for_structuring(chunk_text, filename, category)
            all_questions.extend(extracted)
        except Exception as e:
            logger.error(
                f"[LLM] Erreur sur chunk {chunk_idx + 1} de '{filename}': {e}",
                exc_info=True
            )
            # Continue processing remaining chunks even if one fails
            continue

    logger.info(
        f"[LLM] '{filename}' → {len(all_questions)} question(s) structurée(s) par l'Agent Agno."
    )

    # ── Step 4: Pydantic → dict conversion ───────────────────────────────────
    questions_dicts = [pydantic_to_dict(q) for q in all_questions]
    return resolve_llm_images(questions_dicts)


def resolve_llm_images(questions: list) -> list:
    """
    Post-processes the list of question dicts generated by the LLM:
      1. Cleans brackets [[ ]] from question_images and correction_images.
      2. Appends correct image extension by checking IMAGE_DIR.
      3. Automatically sets has_image = True if any image is associated.
    """
    for q in questions:
        # 1. Clean and resolve question_images
        cleaned_q_imgs = []
        for img in q.get("question_images", []):
            img_clean = re.sub(r'[\[\]\s]', '', img)
            if not img_clean:
                continue
            
            # Find extension in IMAGE_DIR
            found_filename = None
            for ext in [".png", ".jpg", ".jpeg", ".gif"]:
                base, _ = os.path.splitext(img_clean)
                test_file = f"{base}{ext}"
                if os.path.exists(os.path.join(IMAGE_DIR, test_file)):
                    found_filename = test_file
                    break
            
            if found_filename:
                cleaned_q_imgs.append(found_filename)
            else:
                base, ext = os.path.splitext(img_clean)
                if not ext:
                    img_clean = f"{img_clean}.png"
                cleaned_q_imgs.append(img_clean)
        
        q["question_images"] = cleaned_q_imgs

        # 2. Clean and resolve correction_images
        corr = q.get("correction") or {}
        cleaned_c_imgs = []
        for img in corr.get("correction_images", []):
            img_clean = re.sub(r'[\[\]\s]', '', img)
            if not img_clean:
                continue
            
            # Find extension in IMAGE_DIR
            found_filename = None
            for ext in [".png", ".jpg", ".jpeg", ".gif"]:
                base, _ = os.path.splitext(img_clean)
                test_file = f"{base}{ext}"
                if os.path.exists(os.path.join(IMAGE_DIR, test_file)):
                    found_filename = test_file
                    break
            
            if found_filename:
                cleaned_c_imgs.append(found_filename)
            else:
                base, ext = os.path.splitext(img_clean)
                if not ext:
                    img_clean = f"{img_clean}.png"
                cleaned_c_imgs.append(img_clean)
        
        corr["correction_images"] = cleaned_c_imgs

        # 3. Synchronize has_image flag
        if q["question_images"] or corr["correction_images"]:
            q["has_image"] = True

    return questions


def run_hybrid_pipeline(filepath: str, filename: str, category: str) -> list:
    """
    Hybrid cooperative extraction pipeline:
      1. Parse locally using rules-based offline parser (DOCX/PDF).
      2. Validate structure to identify question-specific anomalies.
      3. Call targeted LLM salvager to rebuild any failed or incomplete options.
      4. Call targeted LLM refiner to qualification logically (RJ/RF) and K-type assertions.
    """
    from core.docx import parse_docx_to_qcm
    from core.pdf import parse_pdf_to_qcm
    from core.validator import validate_qcm_structure
    from core.hybrid_refiner import refine_questions_logic_and_ktype, salvage_failed_questions

    ext_lower = filename.lower()
    
    # 1. Parse locally (fast, local, anchors images & formulas)
    logger.info(f"[Hybride] Étape 1 : Parsing local déterministe de '{filename}'...")
    if ext_lower.endswith(".docx"):
        questions = parse_docx_to_qcm(filepath, category)
    elif ext_lower.endswith(".pdf"):
        questions = parse_pdf_to_qcm(filepath, category)
    else:
        logger.warning(f"[Hybride] Format non supporté : {filename}")
        return []
        
    if not questions:
        logger.warning(f"[Hybride] Aucune question extraite localement de '{filename}'.")
        return []
        
    # 2. Validate to detect structural anomalies
    valid_count, errors, anomalies = validate_qcm_structure(questions)
    
    # 3. Targeted Salvage if anomalies found in option letters or empty inputs
    if anomalies:
        logger.info(f"[Hybride] Étape 2 : {len(anomalies)} anomalie(s) détectée(s). Lancement du rattrapage IA...")
        questions = salvage_failed_questions(questions, anomalies, {})
        # Re-validate
        valid_count, errors, anomalies = validate_qcm_structure(questions)
    else:
        logger.info("[Hybride] Étape 2 : Structure locale valide. Aucun rattrapage requis.")
        
    # 4. Refine logical types, K-types, and correct options alignment
    logger.info(f"[Hybride] Étape 3 : Raffinage sémantique fin (logic_type, K-Type)...")
    questions = refine_questions_logic_and_ktype(questions, anomalies)
    
    return questions

